services:
  - type: web
    name: nutrify-ke
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
